-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 21:03:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idioma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idioma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idioma` DEFAULT CHARACTER SET latin1 ;
USE `idioma` ;

-- -----------------------------------------------------
-- Table `idioma`.`tipopalabra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`tipopalabra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(46) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`idioma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(46) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`diccionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`diccionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(46) NOT NULL,
  `IDidioma` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDidioma_idx` (`IDidioma` ASC) VISIBLE,
  CONSTRAINT `IDidioma`
    FOREIGN KEY (`IDidioma`)
    REFERENCES `idioma`.`idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`palabra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`palabra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(46) NULL,
  `pronunciacion` VARCHAR(46) NULL,
  `significado` VARCHAR(46) NULL,
  `observacion` VARCHAR(500) NULL,
  `IDdiccionario` INT NULL,
  `IDtipo_palabra` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDdiccionario_idx` (`IDdiccionario` ASC) INVISIBLE,
  INDEX `IDtipo_palabra_idx` (`IDtipo_palabra` ASC) VISIBLE,
  CONSTRAINT `IDdiccionario`
    FOREIGN KEY (`IDdiccionario`)
    REFERENCES `idioma`.`diccionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDtipo_palabra`
    FOREIGN KEY (`IDtipo_palabra`)
    REFERENCES `idioma`.`tipopalabra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`verbo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`verbo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(46) NOT NULL,
  `pronunciacion_infinitivo` VARCHAR(46) NULL,
  `pasado` VARCHAR(46) NULL,
  `futuro` VARCHAR(46) NULL,
  `presente_simple` VARCHAR(46) NULL,
  `observaciones` VARCHAR(500) NULL,
  `tipo_verbo` TINYINT NOT NULL,
  `pronunciacion_pasado` VARCHAR(46) NULL,
  `pronunciacion_futuro` VARCHAR(46) NULL,
  `pronunciacion_presente_continuo` VARCHAR(46) NULL,
  `IDtipo_palabra` INT NULL,
  `IDdiccionario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDdiccionario_idx` (`IDdiccionario` ASC) VISIBLE,
  INDEX `IDtipo_palabra_idx` (`IDtipo_palabra` ASC) VISIBLE,
  CONSTRAINT `IDtipo_palabra`
    FOREIGN KEY (`IDtipo_palabra`)
    REFERENCES `idioma`.`tipopalabra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDdiccionario`
    FOREIGN KEY (`IDdiccionario`)
    REFERENCES `idioma`.`diccionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`guia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(46) NOT NULL,
  `tema` VARCHAR(46) NOT NULL,
  `titulo` VARCHAR(46) NOT NULL,
  `parrafo1` VARCHAR(500) NOT NULL,
  `parrafo2` VARCHAR(500) NULL,
  `parrafo3` VARCHAR(500) NULL,
  `IDidioma` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDidioma_idx` (`IDidioma` ASC) VISIBLE,
  CONSTRAINT `IDidioma`
    FOREIGN KEY (`IDidioma`)
    REFERENCES `idioma`.`idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idioma`.`ejemplo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idioma`.`ejemplo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(46) NOT NULL,
  `contenido` VARCHAR(500) NOT NULL,
  `IDguia` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDguia_idx` (`IDguia` ASC) VISIBLE,
  CONSTRAINT `IDguia`
    FOREIGN KEY (`IDguia`)
    REFERENCES `idioma`.`guia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
